import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import '@/app/globals.css';
import { Toaster } from '@/components/ui/toaster';
import Providers from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Trainer DB',
  // description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Assign Inter to a CSS variable
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins', // Assign Poppins to a CSS variable
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
